spring.application.name=vsms

server.port=8081

spring.datasource.url=jdbc:mysql://tokaido.proxy.rlwy.net:20297/railway
spring.datasource.username=root
spring.datasource.password=CYhABakQCKZnijkPkrWCbTzbOfYoGOjP

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
